## Disclaimer - This GitHub Actions workflow updates the  work progress status for pipelines.

# Name the workflow
name: pipeline_status

# Define when it runs
on:
  push:
    branches:
      - dev

# Jobs that define the workflow
jobs:

  # A job to update the pipelines statuses
  update-status:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT

    - name: Update the wiki file with new pipeline statuses
      run: |
        echo "wiki" > pipeline_status.md
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Pipeline status updated"
        git push
