## Disclaimer - This GitHub Actions workflow updates the  work progress status for pipelines.

# Name the workflow
name: pipeline_status

# Define when it runs
on:
  push:
    branches:
      - dev

permissions:
  repository-projects: write

# Jobs that define the workflow
jobs:

  # A job to update the pipelines statuses
  update-status:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout wiki
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}

    - name: Update the wiki file with new pipeline statuses
      run: |
        echo "wiki" > pipeline_status.md
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Pipeline status updated"
        git push
