name: pull_request

on: pull_request

jobs:
  pr-job:
    runs-on: ubuntu-latest
    outputs:
      teams: ${{ steps.hi.outputs.teams }}
    steps:
    - name: Say Hi
      id: hi
      run: |
        echo "Run by pull_request"
        teams=05462315
        echo "teams=$teams" >> $GITHUB_OUTPUT
        echo ":rocket: `pr-job` summary :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- value is $teams" >> $GITHUB_STEP_SUMMARY

  message-job:
    needs: pr-job
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            The value is : ${{ needs.pr-job.outputs.teams }}