name: push

on:
  push:
    branches-ignore:    
      - 'main'

jobs:
  pr-job:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hi
      run: echo "Run by push"
    - name: Get config
      run: |
        echo ${{ vars.TEST_CONFIG }} > test_gonfig.toml
        cat test_gonfig.toml
