## Disclaimer - This GitHub Actions workflow runs all the tests for changed pipelines.

# Name the workflow
name: pipeline_tests

# Define when it runs
on:
  push:

# Jobs that define the workflow
jobs:

  # A job to run the tests
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v3

    - name: Export test results
      if: ${{ always() }}
      run: |
        {
          echo "report_team<<EOF"
          cat test_file.txt
          echo EOF
        } >> "$GITHUB_ENV"
        echo "$report_team"

  # A job to report the test results
  tests-report:
    needs: pytest
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
    - name: Report results on step summary
      run: |
        # Start report
        echo "# Correlation values" >> $GITHUB_STEP_SUMMARY
        echo "Unthresholded maps, reproduced vs. results" >> $GITHUB_STEP_SUMMARY
        echo "Correlation values are sorted from hypotheses 1 to 9" >> $GITHUB_STEP_SUMMARY

        # Start report table
        echo "| Team    | Number of subjects | Test status | Correlation values |" >> $GITHUB_STEP_SUMMARY
        echo "| -------- | ------- | ------- | ------- |" >> $GITHUB_STEP_SUMMARY

        # Loop through test report files
        echo "$report_team" >> $GITHUB_STEP_SUMMARY

    - name: Checkout wiki
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}.wiki
        path: wiki

    - name: Report results on the project's wiki
      run: |
        # Loop through test report files & write them to the corresponding wiki page
        echo "# Correlation values for pipeline TEST" > wiki/pipeline_test.md
        echo "Unthresholded maps, reproduced vs. results" >> wiki/pipeline_test.md
        echo "Correlation values are sorted from hypotheses 1 to 9" >> wiki/pipeline_test.md
        echo "These values were calculated by GitHub Actions run [# $GITHUB_RUN_ID]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" >> wiki/pipeline_test.md
        echo "| Team    | Number of subjects | Test status | Correlation values |" >> wiki/pipeline_test.md
        echo "| -------- | ------- | ------- | ------- |" >> wiki/pipeline_test.md

        # Retrieve the report from GITHUB_ENV, as set up by the pytest job
        echo "$report_team" >> wiki/pipeline_test.md

        # Push changes
        cd wiki
        git config user.name github-actions
        git config user.email github-actions@github.com

        # Test if there are changes in the repository before commiting
        if [[ $(git diff --name-only) ]]; then
          git add .
          git commit -m "Pipeline status updated"
          git push
        fi
