name: push

on:
  push:
    branches-ignore:    
      - 'main'

jobs:
  pr-job:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hi
      run: echo "Run by push"
    - name: Write to GITHUB_ENV
      run: |
        team="2T6S"
        report_value="test"
        echo "report_team-$team=$report_value" >> $GITHUB_ENV

  post-job:
    runs-on: ubuntu-latest
    needs: pr-job
    steps:
    - name: Retrieve value from GITHUB_ENV
      run: |
        team="2T6S"
        echo $(report_team-$team)
