name: push

on:
  push:
    branches-ignore:    
      - 'main'

jobs:
  pr-job:
    runs-on: self-hosted
    steps:
    - name: Say Hi
      run: echo "Run by push"
    - name: Get version
      run: ls /data/original/ds001734/
    - name: Get config
      run: |
        echo "${{ vars.TEST_CONFIG }}" > test_gonfig.toml
        cat test_gonfig.toml
