name: push

on:
  push:
    branches-ignore:    
      - 'main'

jobs:
  pr-job:
    runs-on: self-hosted
    steps:
    - name: Say Hi
      run: echo "Run by push"
    - name: Get version
      run: ls /data/original/ds001734/
    - name: Get config
      run: |
        echo "${{ vars.TEST_CONFIG }}" > test_gonfig.toml
        cat test_gonfig.toml
    - name: Write to GITHUB_ENV
      run: |
        team="2T6S"
        report_value="test"
        echo "report_team-$team=$report_value" >> $GITHUB_ENV

  post-job:
    runs-on: self-hosted
    needs: pr-job
    steps:
    - name: Retrieve value from GITHUB_ENV
      run: |
        team="2T6S"
        echo $(report_team-$team)
